# Forward Propagation

In [7]:
import numpy as np
import math

## **Create a NeuralNetwork class**

In [127]:
class NeuralNetwork():
    def __init__(self, dims):
        # take inputs dims = list of integers, number of nodes in each layer
        # create self.layers = list of layer weights as np.arrays
        # create self.bias_layers = list of layer weights as np.arrays (vectors)
        # also store self.num_layers
        self.layers = [np.zeros([dims[i], dims[i+1]]) for i in range(len(dims) - 1)]  
        self.bias_layers = np.array([[-1] * dims[x + 1] for x in range(len(dims) - 1)])
        self.num_layers = dims
    
    def randomize_weights(self, min=-1, max=1):
        newLayers = []
        newBiasLayers = []
        for l,b in zip(self.layers, self.bias_layers):
            #print(np.random.uniform(min,max,[l.shape[0], l.shape[1]]))
            newLayers.append(np.random.uniform(min,max,[l.shape[0], l.shape[1]]))
            newBiasLayers.append(np.random.uniform(min,max,len(b)))
            #print(newLayers)
        #print("NEW LAYERS: " + str(newLayers))
        self.layers = newLayers
        #print("SELF LAYER: " + str(self.layers))
        self.bias_layers = newBiasLayers
        # loop through self.layers and self.bias_layers
        # set all values to random.uniform between min and max
        
    
    def print_layers(self):
        for l,b  in zip(self.layers, self.bias_layers):
            print("layer")
            print(l)
            print("bias")
            print(b)
            
        

** Quick check of initializer **

In [128]:
nn = NeuralNetwork([2,4,1])
nn.print_layers()

layer
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
bias
[-1, -1, -1, -1]
layer
[[0.]
 [0.]
 [0.]
 [0.]]
bias
[-1]


In [129]:
np.random.seed(101)
(nn.randomize_weights())

In [130]:
nn.print_layers()

layer
[[ 0.03279726  0.14133517 -0.94305155 -0.65695669]
 [ 0.37055396  0.66779373 -0.38606756  0.78722616]]
bias
[ 0.44308772 -0.62012209  0.10845518 -0.29573609]
layer
[[-0.63621519]
 [ 0.57120352]
 [ 0.93096644]
 [-0.53529268]]
bias
[-0.83287713]


** Define sigmoid(x,k) with k default value=1 **

In [90]:
def sigmoid(x,k=1):
    return 1 / (1 + math.exp(-k * x))

** Define step(x) **

In [23]:
def step(x):
    return 1 if x > 0 else 0

**Define forward_propagate(NN, x, A, verbose)**
  * This returns the (vector) output of feeding input vector "x" into Neural Net NN, with activation function A.
  * The 'verbose' flag tells whether to print the output of each layer. Default is False

In [181]:
def forward_propagate(NN, x, A, verbose = False):
    newInput = x
    for l,b  in zip(NN.layers, NN.bias_layers):
        output = np.dot(newInput, l)
        output = output + b
        output = [A(x) for x in output]
        print("OUTPUT: " + str(output))
        #for x in range(output):
            #output[x] = step(output[x])
        newInput = output
    return output
    
    ## define this
    pass

# Test Output

Check the following outputs against your code

** Set the random seed to 101. Create a 2,2,1 Neural Network. Randomize its weights and print the layers **

In [176]:
np.random.seed(101)
NN = NeuralNetwork([2,2,1])
NN.randomize_weights()
NN.print_layers()

layer
[[ 0.03279726  0.14133517]
 [-0.94305155 -0.65695669]]
bias
[0.37055396 0.66779373]
layer
[[-0.38606756]
 [ 0.78722616]]
bias
[0.44308772]


** Define an input vector [10,20] and propagate it through the NN above. Show the output of each layer. **

In [177]:
x = [10,20]

forward_propagate(NN,x,sigmoid,verbose=True)

OUTPUT: [-18.16250442 -11.05798829]
OUTPUT: [-1.25009615]


array([-1.25009615])

** Create a 10,20,20,5 neural network with random weights and print its layers **

In [182]:
np.random.seed(101)
NN = NeuralNetwork([10,20,20,5])
NN.randomize_weights()
NN.print_layers()

layer
[[ 3.27972554e-02  1.41335174e-01 -9.43051547e-01 -6.56956688e-01
   3.70553963e-01  6.67793725e-01 -3.86067561e-01  7.87226159e-01
   4.43087724e-01 -6.20122092e-01  1.08455182e-01 -2.95736092e-01
  -6.36215195e-01  5.71203524e-01  9.30966445e-01 -5.35292676e-01
  -8.32877133e-01  2.07096845e-01  4.57985515e-01 -4.47522343e-01]
 [ 3.70612658e-01  3.57349484e-02 -9.03030925e-01 -7.24261525e-01
  -6.26065148e-01  9.88635802e-01  4.13307934e-02  1.57579071e-01
   4.69638117e-01  8.39235445e-02  8.26307115e-01  6.15840302e-01
  -1.94004339e-01 -2.85551314e-01  9.05753429e-01 -3.12736844e-01
   7.30199633e-01  6.60555424e-01  7.63228985e-02  8.44938745e-01]
 [-8.05707040e-01 -7.94305014e-01  4.03014591e-01  7.80959738e-01
  -6.80879398e-01 -4.48854910e-01  3.44983059e-01 -6.71393752e-01
   4.02742273e-01 -2.47295556e-02  3.61355536e-01  4.30963847e-02
  -9.13206611e-01 -5.52126793e-01  1.50410174e-01 -7.59132680e-01
   2.33427602e-04 -7.23980863e-01 -8.94383198e-01 -6.43446155e-01]
 

** Define a random length-10 input vector with values uniformly chosen from -10 to 10 **

In [183]:
x=np.random.uniform(-10,10,10)
print(x)

[ 3.82026751 -4.09516281  9.00299411  5.1962566  -1.17728974 -0.42593198
  7.48816421  6.76063176  3.35401895 -7.81254613]


** Propagate the vector through the neural network above **

In [184]:
forward_propagate(NN,x,sigmoid)

OUTPUT: [3.954184220094227e-09, 0.18031640053853767, 0.999999999685252, 0.9999978880134451, 0.9735127870592886, 0.2796785490963354, 0.9990402069089881, 3.972829909805537e-05, 3.7873208989433196e-05, 0.4364485205723979, 0.5454617109000136, 0.9639534333385044, 1.793121754327536e-08, 0.9999977419361448, 3.940082635289404e-06, 1.7280244654755324e-07, 0.9999791730652078, 8.005742761606834e-05, 0.9973312354672711, 9.584623704971306e-08]
OUTPUT: [0.787703745215095, 0.0325024703714911, 0.09825311463331803, 0.265258223892669, 0.329931161782098, 0.4892219974741317, 0.5914178236753871, 0.4436430865525743, 0.2783956376464578, 0.20514537894375431, 0.6548438980183716, 0.38135586753695977, 0.8696400410464221, 0.5837757556365304, 0.6470008113104989, 0.597413841682434, 0.0398109562282774, 0.4392887215940602, 0.6949000412641407, 0.24480587454324604]
OUTPUT: [0.4379818015674841, 0.8084876977290151, 0.6964641614173902, 0.353029657809123, 0.09964303156900668]


[0.4379818015674841,
 0.8084876977290151,
 0.6964641614173902,
 0.353029657809123,
 0.09964303156900668]